# Generated by Django 3.0.2 on 2020-01-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('spent_money', models.IntegerField()),
                ('gems', models.CharField(max_length=50)),
            ],
        ),
    ]
